name: Deploy staging

on:
  push:
    branches:
      - main


jobs:
  test-and-build:
    uses: ./.github/workflows/test-and-build.yml
    with:
      flow: deploy-main
      branch: main
      configuration: prod
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: [test-and-build]
    steps:
      - name: Checkout [${{ inputs.branch }}]
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - uses: appleboy/scp-action@master
        name: Deploying next.js build
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/apps/devchoices-next/exported/.,!node_modules"
          strip_components: 4
          # The path is based on the directory where the user logged into the server starts
          target: "~/domains/choiceof.dev/public_html"
      - name: create and .env.local file for php
        run: |
          touch .env.local
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env.local
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env.local
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.local
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env.local
      - uses: appleboy/scp-action@master
        name: Deploying php files
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ".env.local,php/.,!node_modules"
          # The path is based on the directory where the user logged into the server starts
          target: "~/domains/choiceof.dev/public_html"
      - name: Launch Semantic release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release


