name: Deploy staging

on:
  push:
    branches:
      - main
jobs:
  test-and-build:
    uses: ./.github/workflows/test-and-build.yml
    with:
      flow: deploy-main
      branch: main
      configuration: prod

  deploy:
    runs-on: ubuntu-latest
    needs: [test-and-build]
    steps:
      - name: Checkout [${{ inputs.branch }}]
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/apps/devchoices-next/exported/.,!node_modules"
          strip_components: 4
          # The path is based on the directory where the user logged into the server starts
          target: "~/domains/choiceof.dev/public_html"
      - name: Launch Semantic release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release


